src/modules/query.js
=> use APPROX_COUNT_DISTINCT for size queries

dist/mapd-crossfilter.js
@Drecula I'm not sure why the mapd-crossfilter in /dist was out of phase with a clean build, but I wanted to get rid of this debugger statement:
https://github.com/mapd/mapd-crossfilter/blob/master/dist/mapd-crossfilter.js#L16123
=> Rebuilt mapd-crossfilter so it gets rid of a "debugger" statement

src/mapd-crossfilter.js
=> add nulls first last to orderby queries

src/mapd-crossfilter.js
=> Clear all cache

src/mapd-crossfilter.js
=> improved regex for uncast fn, fixes immerse 3825

dist/mapd-crossfilter.js, package-lock.json, package.json, src/mapd-crossfilter.js, test/crossfilter.spec.js
=> Modify getFilterString to take a dimensionIndex to ignore

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
Relates with https://github.com/mapd/mapd-charting/pull/216
=> added function to get dimension name

dist/mapd-crossfilter.js
=> updating dist crossfilter to 2283e79a

dist/mapd-crossfilter.js, package.json, src/mapd-crossfilter.js, test/crossfilter.spec.js
=> Correct the magic number for Knuths multiplicative hash

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
=> ST_Contains and ST_Intersects filters on dimension

dist/mapd-crossfilter.js, src/mapd-crossfilter.js, test/crossfilter.spec.js
Related to fix for https://jira.omnisci.com/browse/FE-7543 in Immerse
=> [FE-7543] Scope field names in dimension expressions to table

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
Related to fix for [FE-7633](https://jira.omnisci.com/browse/FE-7633)
=> [FE-7633] Only scope fields to table if a column name that does not contain '('

dist/mapd-crossfilter.js, src/mapd-crossfilter.js, test/crossfilter.spec.js
=> [FE-8323] use thirty one bit in MOD sampling

dist/mapd-crossfilter.js, src/mapd-crossfilter.js, test/crossfilter.spec.js
This is required for: https://github.com/omnisci/mapd-immerse/pull/5371
=> [FE-8324] - Expose method to get tableDescriptor

dist/mapd-crossfilter.js, src/mapd-crossfilter.js, test/crossfilter.spec.js
Part of the ongoing binning work, this brings the equivalent mod from metis pull 59.
Fixes binning to stuff last values into the last bin.
Closes [FE-8602](https://jira.omnisci.com/browse/FE-8602)
=> [FE-8602] - extended case mods to mapd-crossfilter

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
Immerse companion PR: https://github.com/omnisci/mapd-immerse/pull/5659
=> [FE-9024] -  Fix relative filter making 0 length time span queries

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
Simple addition of a getter for drillDownFilter
=> add a getDrillDownFilter method

src/mapd-crossfilter.js
Added a few getters that I need for my adapter work
=> [FE-9023] added some accessors needed for adapter

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
Adds functionality that is needed for FE-9095, but does not finish that ticket.
=> [FE-9095] support for toggling filters

src/mapd-crossfilter.js, test/crossfilter.spec.js
Reverts omnisci/mapd-crossfilter#100
=> Revert "[FE-9812] Restore `TIMESTAMP(3)` type annotation to string literals"

dist/mapd-crossfilter.js, src/mapd-crossfilter.js, test/crossfilter.spec.js
This reverts commit 60b7a8725d64b69a443a1d8da56b91a584bb134f.
The fix for FE-9355 was incorrect (due to incorrect specs) and ended up causing more problems than it fixed. So this reverts it. See the Jira for this issue for more details.
=> [FE-9829] Revert FE-9355/#97

dist/mapd-crossfilter.js, src/mapd-crossfilter.js
=> [FE-7925] add option to exclude a specific crossfilter from valueAsync

package-lock.json, package.json
Just a package bump to version 1.2.0 to prepare for publishing.
=> Version 1.2.0
